basic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.db.models.fields import PositiveSmallIntegerField
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', showmain, name="showmain"),
    path('first/', first, name="first"),
    path('second/', second, name="second"),
    path('<str:id>', detail, name="detail"),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('posts/', posts, name="posts"),
    path('edit/<str:id>', edit, name="edit"),
    path('update/<str:id>', update, name="update"),
    path('delete/<str:id>', delete, name="delete"),

]

users/urls.py
from django.urls import path
from .import views

app_name = "users"
urlpatterns = [
    path('mypage/', views.mypage, name="mypage"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to = "post/", blank=True, null=True)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:20]

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post
from  django.utils import timezone
# Create your views here.

def showmain(request):
    posts = Post.objects.all()
    return render(request, 'main/mainpage.html', {'posts':posts})

def first(request):
    return render(request, 'main/first.html')

def second(request):
    return render(request, 'main/second.html')

def posts(request):
    posts = Post.objects.all()
    return render(request, 'main/posts.html', {'posts':posts})

def detail(request, id):
    post = get_object_or_404(Post, pk = id)
    return render(request, 'main/detail.html', {'post':post})

def new(request):
    return render(request, 'main/new.html')

def create(request):
    new_post = Post()
    new_post.title = request.POST['title']
    new_post.writer = request.user
    new_post.pub_date = timezone.now()
    new_post.body = request.POST['body']
    new_post.image = request.FILES.get('image')
    new_post.save()
    return redirect('main:detail', new_post.id)

def edit(request, id):
    edit_post = Post.objects.get(id = id)
    return render(request, 'main/edit.html', {'post':edit_post})

def update(request, id):
    update_post = Post.objects.get(id=id)
    update_post.title = request.POST['title']
    update_post.writer = request.user
    update_post.pub_date = timezone.now()
    update_post.body = request.POST['body']
    update_post.save()
    return redirect('main:detail', update_post.id)

def delete(request, id):
    delete_post = Post.objects.get(id = id)
    delete_post.delete()
    return redirect('main:posts')

users/views.py
from django.shortcuts import render
from main.models import Post
from django.contrib.auth.models import User
# Create your views here.

def mypage(request):
    user = request.user
    posts = Post.objects.filter(writer=user)
    return render(request, 'users/mypage.html', {'posts':posts})

basic/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>멋사 자소서</title>
</head>
<body>
    {% include 'shared/_navbar.html' %}
   
    {% block content %}

    {% endblock %}

</body>  
</html>

basic/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'main:showmain' %}">Home</a>
     
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          </li>
          <li class="nav-item">
            <a href="{% url 'main:first' %}" class="nav-link" href="#">Introduce1</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'main:second' %}" class="nav-link" href="#">Introduce2</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Account</a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% if user.is_authenticated %} 
              <li><a class="dropdown=item" href="{% url 'users:mypage' %}">Mypage</a></li>
              <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
              {%else%} 
              <li><a class="dropdown-item" href="{% url 'account_login' %}">Login</a></li>
              <li><a class="dropdown-item" href="{% url 'account_signup' %}">Signup</a></li>
              {%endif%}
            </ul>
          </li>
        </ul>
      </div>
    </div>
</nav>
  

main/templates/main/detail.html
{% extends 'base.html' %}
% load static %

{% block content %}

<h1>{{post.title}}</h1>
{% if post.writer %}
{% if 'user' in post.writer.username %}
    <h3>작성자 : {{ post.writer.last_name }} {{ post.writer.first_name }}</h3>
{% else %}
    <h3>작성자 : {{ post.writer }}</h3>
{% endif %}
{% else %}
    <h3>작성자 : 알 수 없음</h3>
{% endif %}


날짜 : {{post.pub_date}}
<hr>
{% if post.image %} 
    <p><img src="{{post.image.url}}" alt="사진"></p>
{% endif %}
<p>{{post.body}}</p>
<a href="{%url 'main:edit' post.id%}">수정하기</a>
<a href="{%url 'main:delete' post.id%}">삭제하기</a>

{% endblock %}

main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
	<h1>글 수정하기</h1>
	<form action="{%url 'main:update' post.id %}" method="post">
		{%csrf_token%}
		<p>제목 : <input type="text" name="title" value="{{post.title}}"></p>
		<p>사진 : <input type="file" name="image">{{post.image}}</p>
		<p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10">{{post.body}}</textarea></p>
		<button type="submit">제출</button>
	</form>
</div>
{% endblock %}

main/templates/main/first.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

    {% block content %} 
    <div class="imagewoman">
      <img src="{%static 'images/image4.jpg'%}" alt="컴퓨터하는 사진" width="700" height="600">
    </div>

    <br>
    <br>


    <div class="center">
        <big><h2><strong><멋쟁이 라이언 지원공고></strong></h2></big>
      <h5>멋쟁이 아기 라이언들을 뽑습니다. 고민은 NO! 지금 바로 지원하세요~</h5>
      <br>
      <br>
      
      <h4>지원방법</h4>

      <table>
        <td> <div class="space">
         <ol>
            <li> 개성있고 열정이 넘치는 당신은 우리의 인재상! 멋쟁이 라이언에 지원해보세요~</li>
            <li> 모집기간: 5/3 ~ 5/7</li>
            <li> 본인을 소개하는 질문 2개만 작성해주시면 지원완료!</li>
            <li> 지원은 '제출' 버튼 하나만 클릭하면 끝!</li>
            <li> 선발결과는 5월 12일 오후 7시에 나옵니다. </li>
            <li> 아기라이언이 될 수 있는 기회는 지금뿐! 여러분 많관부~</li>
         </ol>
        </td>
     </table>
 
    </div>

   <div class="talk">
      <p>와! 멋쟁이 라이언이잖아!!</p>
      <p>나도 아기라이언이 되고 싶당ㅠㅠ</p>
      <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'고민은 No'라고 되어있으니까 </p>
      <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;한 번 지원해보자ㅎㅎ</p>
   </div>
   {% endblock %}
  

main/templates/main/mainpage.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %} 
  <div class="container">
    <img src="{%static 'images/image1.jpg'%}" alt="한강 사진" width="1250">
  </div>

  <br>
  <div class="image">
    
    <img src="{%static 'images/image2.png'%}" alt="인사 사진" width="300" height="300">
    
    <img src="{%static 'images/image3.jpg'%}" alt="말풍선 사진" width="400" height="300">
    
 
  </div>


  <div class="center">
    <br>
    <h1><strong>안녕하세요!</strong></h1>
    <h5>저는</h5>
    <h3>국제통상학과 2학년</h3>
  <h2>김영서입니다 :)</h2>

  <p>저는 학교 생활을 못 해보아서 앞으로 해보고 싶은 것이 많습니다...!</p>
  </div>

  <div class="bottom">
    <br>
    <br>
    <p>저에 대한 구체적인 정보는</p>
    <p>다음 페이지에서 보여드릴게요!</p>
  </div>

  <h2><a href="{%url 'main:new'%}">글쓰기</a></h2>
  
  <h1>글 목록</h1>
  <div>
    {% for post in posts %} 
    <div>
      <h3>{{post.title}}</h3>
      {{post.writer}}<br>
      {{post.summary}}
      <a href="{%url 'main:detail' post.id%}">...자세히</a>
      <br>
    </div>
    {%endfor%}
  </div>



{% endblock %}
  

main/templates/main/new.html
{% extends 'base.html' %}
% load static %

{% block content %}

<form action="{%url 'main:create' %}" method="post" enctype="multipart/form-data">
    {%csrf_token%} 
    <p>제목 : <input type="text" name="title"></p>
    <p>사진 : <input type="file" name="image"></p>
    <p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10"></textarea></p>
    <button type="submit">제출</button>
</form>


{% endblock %}

main/templates/main/posts.html
{% extends 'base.html' %} 
{% load static %} 

{% block content %} 
<div class="container">
    {% if user.is_authenticated %}
    <h1>글 목록</h1>

    <div>
        {% for post in posts %}
        <div>
            <h3>{{post.title}}</h3>
            {% if blog.writer %}
            {% if 'user' in blog.writer.username %}
                작성자 : {{ blog.writer.last_name }} {{ blog.writer.first_name }}
            {% else %}
                작성자 : {{ blog.writer }}
            {% endif %}
            {% else %}
                작성자 : 알 수 없음
            {% endif %}
            <br><hr>
        </div>
        {%endfor%}
    </div>
    {%else%} 
        <h3>로그인 후 이용 가능</h3>
        <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
        <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
    {%endif%}
</div>
{% endblock %}

main/templates/main/second.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}

<div class="container">

</div>


<div class="introduce">
<big><h4><strong><자기소개서></strong></h4></big>
<br>
<big><h5><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. 본인의 기본정보를 알려주세요.</strong></h5></big>
<br>
    <table>
    <td>
        <ul>
            <li> 이름: 김영서</li>
            <li> 학번: 20</li>
            <li> 나이: 21세</li>
            <li> 학과: 국제통상학과</li>
        </ul>
    </td>
    </table>
<br>
<br>
<br>
<big><h5><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. 본인의 TMI를 free하게 대방출해주세요.</strong></h5></big>
<br>
    <table>
    <td> <div class="table">
        <br>
        &nbsp;&nbsp;저는 밝고 활발하며 노는 것을 좋아하는 '뽀로로끼(?)'가 있는 열정 만수르입니다.
        이러한 성격 덕에 활동적이고 생산적인 일을 하는 것을 좋아합니다. 김영서 활용 설명서에 따르면 생산적인 활동을 할 때 좋아하는 노래를 들을 때 더욱 효율을 높일 수 있다고 합니다. 
        요즘 코로나가 심해져서 집에서만 놀게 되어 숨겨진 저의 취미를 하나씩 발굴하고 있습니다. 현재는 요리하기, 물고기 키우기, 식물 기르기, 게임하기 등을 즐기고 있습니다.
        그러다 광합성이 필요하면 산책이나 피크닉을 가기도 합니다. 음식은 크게 가리지 않지만 마라탕과 떡볶이를 가장 사랑합니다. 커피도 정말 좋아해서 카페 알바도 하기 시작했습니다. 
        알바는 물론 좀 힘들지만^^ 하핳 그래도 음료를 만드는 것은 여전히 재미있습니다. 이외에도 대학생 때 꼭 해보고 싶은 것들이 있습니다. 
        작년에 다 취소되었던 MT, 신환회, 새터, 축제 등은 정말 안타깝게 못 해보았지만 동아리 활동은 올해 해볼 수 있어서 정말 다행입니다ㅠㅠ 
        저의 버킷리스트를 멋사와 함께 이룰 수 있어서 더욱 기쁩니다!!! 하나하나 배울 때마다 흥미롭고 신기해서 재미있게 배우고 있습니다. 
        평범하고 평범한 저의 자기소개를 봐주셔서 감사합니다 :)
    </td>
    </table>

    <br>
    <br>

<form action="base.html">
    <input type="submit">
</form>


</div>

{% endblock %}

users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block content %} 
<div class="containe">
    <h1>{{user.username}}</h1>
    <div>
        {% for post in posts %} 
            <a href="{% url 'main:detail'post.id %}">{{post.title}}</a><hr>
        {%endfor%}
    </div>
</div>
{%endblock%}